### PR TITLE
Feature/login page

### PR DESCRIPTION
**Pull request by dan1229**

### CODE REVIEW

**Comment by oudeismetis** [comment]
@bwennuh (and maybe @mayakeeley ) This is a PR one or more of us should collab on.

**Comment by dan1229** [comment]
For context - another pr was already approved and merged into this (https://github.com/thinknimble/tn-spa-bootstrapper/pull/37) this includes some setup docs, app.json, etc.

**Comment by oudeismetis** [comment]
This PR is very out of date and new PRs have added some of this functionality.
There is some good stuff here though so some of this will be pulled into a new PR soon.
Will close this PR once that is true.

**Comment by oudeismetis** [comment]
This PR is very out of date and new PRs have added some of this functionality.
There is some good stuff here though so some of this will be pulled into a new PR soon.
Will close this PR once that is true.

**Comment by oudeismetis** [comment]
This PR is very out of date and new PRs have added some of this functionality.
There is some good stuff here though so some of this will be pulled into a new PR soon.
Will close this PR once that is true.

**Comment by oudeismetis** [comment]
https://github.com/thinknimble/tn-spa-bootstrapper/pull/61 implements this feature.
https://github.com/thinknimble/tn-spa-bootstrapper/pull/45 also has some of this.

**Pull request closed without merging**
