### PR TITLE
Removed test code from views/Home

### LINKED ISSUE #73: vue3 client cleanup views/Home
Code in `setup()` should be removed

### PR DESCRIPTION
**Pull request by iMezemz**
fix #73

### CODE REVIEW

**Review by brunogarciagonzalez — CHANGES_REQUESTED** [review]
Thanks for your contribution! Could you also removed the now-unused imports in this file? Sorry I should have included that in the issue!

**Comment by iMezemz** [comment]
No problem, Done..

**Comment by oudeismetis** [comment]
PR closed?

**Comment by oudeismetis** [comment]
@iMezemz Any reason for closing the PR? Feel free to reopen as this was a good change!

**Pull request closed without merging**
