### PR TITLE
vue3 fixed user instantiation after authentication flows

### PR DESCRIPTION
**Pull request by brunogarciagonzalez**
Fixed issue where instance of `User` being added to the store state was empty.

### CODE REVIEW

**Comment by oudeismetis** [comment]
How do you test this?

**Comment by brunogarciagonzalez** [comment]
> How do you test this?

@oudeismetis I tested by running the flow locally and along with logging, used the Vue dev tools to confirm the fix that  this code prevents an empty instance of the clienside `User` model to be added to the `store.state`.

There was a bug where even with an error we were instantiating an empty user instance.
Now we have an updated vue3 `store.getters.isLoggedIn` where the token field of the user (`store.state.user.token`) must be truthy as well, so that improves the `isLoggedIn` getter as a stand-alone improvement. But this PR also fixes the bug of instantiating an empty user instance, where we would rather `store.state.user` remain `null` until a proper login/signup yields a valid instance of the clientside `user` model.

Whenever we fix #63  then `store.getters.isLoggedIn` should be updated again.

**Comment by oudeismetis** [comment]
OK! I'll probably test this tomorrow

**Review by oudeismetis — APPROVED** [review]
tested and confirmed fix

**Pull request merged**
